package domain

import "encoding/json"

type CloudServiceProvider int

const (
	ENUM_CLOUD_SERVICE_PROVIDER_UNKNOWN CloudServiceProvider = iota
	ENUM_CLOUD_SERVICE_PROVIDER_AWS
	ENUM_CLOUD_SERVICE_PROVIDER_AZURE
	ENUM_CLOUD_SERVICE_PROVIDER_GCP
)

const (
	_CLOUD_SERVICE_PROVIDER_UNKNOWN_STR             = "Unknown cloud service provider"
	_CLOUD_SERVICE_PROVIDER_AWS_DEFAULT_STR         = "AWS"
	_CLOUD_SERVICE_PROVIDER_AWS_ALTERNATIVE_1_STR   = "Amazon Web Services"
	_CLOUD_SERVICE_PROVIDER_AWS_ALTERNATIVE_2_STR   = "Amazon"
	_CLOUD_SERVICE_PROVIDER_AZURE_DEFAULT_STR       = "Azure"
	_CLOUD_SERVICE_PROVIDER_AZURE_ALTERNATIVE_1_STR = "Microsoft Azure"
	_CLOUD_SERVICE_PROVIDER_AZURE_ALTERNATIVE_2_STR = "Microsoft"
	_CLOUD_SERVICE_PROVIDER_GCP_DEFAULT_STR         = "GCP"
	_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_1_STR   = "Google Cloud Platform"
	_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_2_STR   = "Google Cloud"
	_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_3_STR   = "Google"
)

func (self CloudServiceProvider) String() string {
	return [...]string{
		_CLOUD_SERVICE_PROVIDER_UNKNOWN_STR,
		_CLOUD_SERVICE_PROVIDER_AWS_DEFAULT_STR,
		_CLOUD_SERVICE_PROVIDER_AZURE_DEFAULT_STR,
		_CLOUD_SERVICE_PROVIDER_GCP_DEFAULT_STR,
	}[self]
}

func (self *CloudServiceProvider) FromString(status string) CloudServiceProvider {
	return map[string]CloudServiceProvider{
		_CLOUD_SERVICE_PROVIDER_UNKNOWN_STR:             ENUM_CLOUD_SERVICE_PROVIDER_UNKNOWN,
		_CLOUD_SERVICE_PROVIDER_AWS_DEFAULT_STR:         ENUM_CLOUD_SERVICE_PROVIDER_AWS,
		_CLOUD_SERVICE_PROVIDER_AWS_ALTERNATIVE_1_STR:   ENUM_CLOUD_SERVICE_PROVIDER_AWS,
		_CLOUD_SERVICE_PROVIDER_AWS_ALTERNATIVE_2_STR:   ENUM_CLOUD_SERVICE_PROVIDER_AWS,
		_CLOUD_SERVICE_PROVIDER_AZURE_DEFAULT_STR:       ENUM_CLOUD_SERVICE_PROVIDER_AZURE,
		_CLOUD_SERVICE_PROVIDER_AZURE_ALTERNATIVE_1_STR: ENUM_CLOUD_SERVICE_PROVIDER_AZURE,
		_CLOUD_SERVICE_PROVIDER_AZURE_ALTERNATIVE_2_STR: ENUM_CLOUD_SERVICE_PROVIDER_AZURE,
		_CLOUD_SERVICE_PROVIDER_GCP_DEFAULT_STR:         ENUM_CLOUD_SERVICE_PROVIDER_GCP,
		_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_1_STR:   ENUM_CLOUD_SERVICE_PROVIDER_GCP,
		_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_2_STR:   ENUM_CLOUD_SERVICE_PROVIDER_GCP,
		_CLOUD_SERVICE_PROVIDER_GCP_ALTERNATIVE_3_STR:   ENUM_CLOUD_SERVICE_PROVIDER_GCP,
	}[status]
}

func (self CloudServiceProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(self.String())
}

func (self *CloudServiceProvider) UnmarshalJSON(data []byte) error {
	var status string
	err := json.Unmarshal(data, &status)
	if err != nil {
		return err
	}
	*self = self.FromString(status)
	return nil
}
