# CAUTION: This file is tracked by git. You should create a copy of this
# template and modify it instead.

### REQUIRED ------------------------------------------------------------------

identity:
  username: ubuntu
  hostname: ubuntu
  # if the password was 'ubuntu', it would be this value
  passwd_sha512: $6$ub67omdRVraNy1bj$POIuPjilvuZjQze6FEVAyiPdLCFF/PAvP22EhCgBnYqGvtUSdunkniyRHMnxxdFhaSd6yrFlvF8ADDtLi.ovx1

ssh_keys:
# copy and paste your ~/.ssh/key.pub file
# - <ssh-algorithm> <pub-key> <owner>

# this section depends on your disk size and preferences
partitions:
  confidential:
    # (cloud disks are not allowed to have non-integer sizes in GB)
    size: 10G

  root:
    # ubuntu-server-minimal:
    # (cloud disks are not allowed to have non-integer sizes in GB)
    # - (absolute minimum) 3G
    # - (minimum) 10G
    # - (recommended) >=25G
    size: 25G

### OPTIONAL ------------------------------------------------------------------
### Uncomment if you want to use

# # Note: check the full file to see what is already set to be installed
# initial_packages:
#   # Examples:
#   - vim
#   - zip


# # Note: check the full file to see what is already set to run
# # Note: will be executed as a privileged user
# late_commands:
#   - 
