mounts:
  - location: "${PROJECT}"
    mountPoint: /home/debian/project
    writable: true
cpus: 4       # default
memory: 6GiB  # default
disk: 150GiB   # default
base:
  - ./base.yaml
param:
  arch: "${ARCH}"
